language: python
python:
  - '3.5'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE=intro_framework_django_Project.settings.travis

services:
  - postgresql

script:
  - python manage.py test

# safelist
branches:
  only:
    - staging
